### PR TITLE
Js to load order details

### PR DESCRIPTION
**Pull request by DNNMonster**
JS to enable loading specific orders from an eid in the path.

### CODE REVIEW

**Comment by leedavi** [comment]
I'm not sure what effects this may have, can you demo it to me please?

**Comment by DNNMonster** [comment]
I think your right.  This is specific to our installation and won't benefit others at this stage.  To demo it you can just alter your url path to the BO orders with a /eid/{ItemId} and as long as the ItemId is valid for the ORDER record it will render the details rather than the list.  Otherwise all links into the BO orders will always render the list.  It's the same approach used for the EditUrl Token to render a specific product versus a list.  We can close it if you prefer or merge it so the capability is in place even though it's not currently in use.  Other integrations may have some likelihood of ending up with this as a requirement.

**Comment by leedavi** [comment]
OK, I've had a think and I think it could be helpful to people and will not effect people if they are not using it..  I'll include,

**Comment by leedavi** [comment]
thx again for your help. :-)

**Pull request merged**
