### PR TITLE
Xpath for EntryUrl token.

### PR DESCRIPTION
**Pull request by DNNMonster**
You might review the other tokens because I think this may apply to others & I expect you can most quickly identify the proper ones.

### CODE REVIEW

**Comment by leedavi** [comment]
Not sure this is right.

I think "genxml/productxml/.." only exist in the "ORDER" record, not the navigation.

**Comment by DNNMonster** [comment]
Yeah I submitted this PR because of what I was seeing in the debugger while viewing an order.  OrderAdminDetail.cshtml uses this token and the paths are not working for product data in an order.  It is used to set the seoname param used in the FriendlyUrl func.  This param will never be accurate from the context of the order details page. This may be un-important.

**Comment by leedavi** [comment]
OK, I see.  I think probably the correct action should be to alter the template or test for the current path and if not there then use the productxml path.

What do you think?

**Comment by DNNMonster** [comment]
Sounds right.  I'll close this PR.

**Pull request closed without merging**
