### PR TITLE
Added an option to calculate shipping on cart total value in place of subtotal (original price)

### PR DESCRIPTION
**Pull request by Rdi3n**
Added an option so shop owners can choose to calculating shipping on subtotal (original price) or calculating shipping on cart total value which already applies discount.

The shipping provider has a new checkbox for this use case and when activated the subtotal (original price) will be replace with subtotal (cart total value).

### CODE REVIEW

**Comment by leedavi** [comment]
OK great!!!

Can I presume that the operation will be exactly the same as previous, by default?  And the user MUST turn it on to change the calculation?

**Comment by leedavi** [comment]
I'll wait for your OK on this.

**Comment by Rdi3n** [comment]
Okay, I have install it on copy of two productions website and everything is working fine!

So you can merge this branch. ✌

**Comment by leedavi** [comment]
Great thx Rodien.

**Pull request merged**
